"""add start_time for tr

Revision ID: 1ab0a96c72c5
Revises: a2e998a1dbee
Create Date: 2024-08-26 16:04:06.314251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab0a96c72c5'
down_revision: Union[str, None] = 'a2e998a1dbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testrecords', sa.Column('start_time', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testrecords', 'start_time')
    # ### end Alembic commands ###
