"""Drop unique constraint on name in testrecord

Revision ID: 6b5b1775d900
Revises: b0ebb580df94
Create Date: 2025-03-12 15:22:47.142808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5b1775d900'
down_revision: Union[str, None] = 'b0ebb580df94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('testrecords_test_name_key', 'testrecords', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('testrecords_test_name_key', 'testrecords', ['test_name'])
    # ### end Alembic commands ###
