"""Add calibration data to Cell model

Revision ID: a425672db17b
Revises: 6b5b1775d900
Create Date: 2025-06-13 18:07:57.476915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a425672db17b'
down_revision: Union[str, None] = '6b5b1775d900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('calibration_x1', sa.Float(), nullable=True))
    op.add_column('cells', sa.Column('calibration_x2', sa.Float(), nullable=True))
    op.add_column('cells', sa.Column('calibration_c', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'calibration_c')
    op.drop_column('cells', 'calibration_x2')
    op.drop_column('cells', 'calibration_x1')
    # ### end Alembic commands ###
