"""Add size column to TestRecord

Revision ID: b0ebb580df94
Revises: 1ab0a96c72c5
Create Date: 2025-01-06 14:33:52.170745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ebb580df94'
down_revision: Union[str, None] = '1ab0a96c72c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testrecords', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testrecords', 'size')
    # ### end Alembic commands ###
